version: '3'

services:
  db:
    container_name: db_mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web_shop
      MYSQL_USER: user-1
      MYSQL_PASSWORD: user-1
    restart: always
    ports:
      - "5432:3306"
    volumes:
      - db_data:/var/lib/mysql
  mongo:
    container_name: db_mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongovolume:/data/db
  consumer:
    container_name: consumer
    restart: on-failure
    build:
      context: ./consumer
      dockerfile: Dockerfile
    depends_on:
      - rabbit
  rabbit:
    container_name: dev_rabbit
    hostname: rabbit
    image: rabbitmq:3.8.9-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5672" ]
      interval: 30s
      timeout: 10s
      retries: 5
  admin_api:
    container_name: admin_api
    build:
      context: ./admin_web
      dockerfile: Dockerfile
    ports:
      - 8010:5000
    volumes:
      - ./app:/app
    links:
      - db
    depends_on:
      - db
    environment:
      APP_ID: 1
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user-1
      MYSQL_PASSWORD: user-1
  catalog_api:
    container_name: catalog_api
    build:
      context: ./catalog_api
      dockerfile: Dockerfile
    ports:
      - 8020:5000
    volumes:
      - ./app:/app
volumes:
  db_data: { }
  mongovolume: